# Generated by Django 3.2.6 on 2024-04-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('fecha', models.DateField(auto_created=True)),
                ('id', models.IntegerField(max_length=10000, primary_key=True, serialize=False)),
                ('ciudad', models.CharField(default=None, max_length=50)),
                ('direccion', models.CharField(default=None, max_length=50)),
                ('estado', models.CharField(default=None, max_length=50)),
                ('tipo', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]